version: '3.3'

services:
  flat:
    build: ./
    command: ./MyFlat
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "MyFlat"
      POSTGRES_PASSWORD: 12345
    ports:
      - 5436:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080